'use strict';
const logger = require('./../../applogger');
const router = require('express').Router();
const {patient} = require('./patientEntity');
const patientCtrl = require('./patientController');
const passport = require('passport');
const Strategy = require('passport-local').Strategy;
router.post('/addPatient',patientCtrl.addPatient);
router.post('/addAppointment',patientCtrl.addAppointment);
router.get('/viewPatients',patientCtrl.viewPatients);
router.post('/viewPatientWithId',patientCtrl.viewPatientWithId);
router.post('/viewAppointment',patientCtrl.viewAppointment);
router.post('/scheduleAppointment',patientCtrl.scheduleAppointment);
router.post('/reScheduleAppointment',patientCtrl.reScheduleAppointment);
router.post('/sendMessage',patientCtrl.sendMessage);
router.post('/cancelAppointment',patientCtrl.cancelAppointment);
router.post('/editProfile',patientCtrl.editProfile);
router.post('/viewParticularAppointment', patientCtrl.viewParticularAppointment);
module.exports = router;
